export const SOCKET_EMIT_USER_WATCH = 'user-watch'
export const SOCKET_EMIT_SET_TOPIC = 'chat-set-topic'
export const SOCKET_EMIT_SET_RECIPIENT = 'chat-set-recipient'
export const SOCKET_EMIT_SEND_PRIVATE_MSG = 'send-private-msg'
export const SOCKET_EMIT_ROOM_CHAT_SEND_MSG = 'room-chat-send-msg'
export const SOCKET_EMIT_LOGIN = 'set-user-socket'
export const SOCKET_EMIT_LOGOUT = 'unset-user-socket'
